countries <- c("Albania", "Algeria", "Andorra", "Armenia", "Austria", "Azerbaijan",
               "Bahrain", "Belarus", "Belgium", "Bosnia and Herzegovina",
               "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark",
               "Egypt", "Estonia", "Faroe Islands", "Finland", "France", "Georgia",
               "Germany", "Gibraltar", "Greece", "Hungary", "Iceland", "Iran",
               "Iraq", "Ireland", "Israel", "Italy", "Jordan", "Kazakhstan",
               "Kosovo", "Kuwait", "Latvia", "Lebanon", "Libya", "Liechtenstein",
               "Lithuania", "Luxembourg", "Macedonia", "Malta", "Moldova",
               "Monaco", "Montenegro", "Morocco", "Netherlands", "Norway",
               "Palestinian Territory", "Poland", "Portugal", "Qatar", "Romania",
               "Russia", "San Marino", "Saudi Arabia", "Serbia", "Slovakia",
               "Slovenia", "Spain", "Sweden", "Switzerland", "Syria", "Tunisia",
               "Turkey", "Turkmenistan", "Ukraine", "United Kingdom", "Uzbekistan",
               "Vatican")

plot(svet, xlim = c(-10, 35), ylim = c(30, 70), axes = TRUE,
     bg = "lightblue", col = "white", border = "lightgray")
divide.world("Slovenia", "Croatia", from = 14.75, to = 15.64, add = TRUE)
divide.world("Slovenia", "San Marino", from = 11.7, to = 14.75, add = TRUE)
divide.world("Slovenia", "Austria", from = 13, to = 15.64, add = TRUE)
divide.world("Croatia", "Austria", from = 15.64, to = 16.53, add = TRUE)
divide.world("Slovenia", "Liechtenstein", from = 11.7, to = 12.7, add = TRUE)
divide.world("Switzerland", "Liechtenstein", from = 8.18, to = 8.81, add = TRUE)
divide.world("Switzerland", "France", from = 3.1, to = 4.88, add = TRUE)
divide.world("Luxembourg", "France", from = 4.1, to = 4.88, add = TRUE)
divide.world("Luxembourg", "Switzerland", from = 4.88, to = 8.18, add = TRUE)
divide.world("Luxembourg", "Liechtenstein", from = 8.18, to = 10.28, add = TRUE)
divide.world("Monaco", "Switzerland", from = 3.6, to = 8.81, add = TRUE)
divide.world("Monaco", "Liechtenstein", from = 8.81, to = 9.84, add = TRUE)
divide.world("Monaco", "Vatican", from = 8.2, to = 10.01, add = TRUE)
divide.world("San Marino", "Italy", from = 13.1, to = 15.38, add = TRUE)
divide.world("San Marino", "Monaco", from = 9.84, to = 10.01, add = TRUE)
divide.world("San Marino", "Liechtenstein", from = 9.84, to = 11.7, add = TRUE)
divide.world("San Marino", "Croatia", from = 14.75, to = 15.4, add = TRUE)
divide.world("Italy", "Vatican", from = 11.1, to = 13.1, add = TRUE)
divide.world("San Marino", "Vatican", from = 10.01, to = 13.1, add = TRUE)
divide.world("Luxembourg", "Belgium", from = 4.1, to = 7, add = TRUE)
divide.world("France", "Belgium", from = 1.85, to = 4.1, add = TRUE)
divide.world("United Kingdom", "Netherlands", from = 0.22, to = 2.4, add = TRUE)
divide.world("United Kingdom", "Belgium", from = 1.85, to = 2.4, add = TRUE)
divide.world("United Kingdom", "France", from = -6.9, to = 1.85, add = TRUE)
divide.world("Netherlands", "Belgium", from = 2.4, to = 7, add = TRUE)
divide.world("Netherlands", "Luxembourg", from = 7, to = 9.19, add = TRUE)
divide.world("Netherlands", "Germany", from = 9.09, to = 9.19, add = TRUE)
divide.world("Luxembourg", "Germany", from = 9.19, to = 10.15, add = TRUE)
divide.world("Czech Republic", "Austria", from = 13, to = 17.05, add = TRUE)
divide.world("Czech Republic", "Slovenia", from = 12.7, to = 13, add = TRUE)
divide.world("Czech Republic", "Liechtenstein", from = 10.28, to = 12.7, add = TRUE)
divide.world("Czech Republic", "Luxembourg", from = 10.15, to = 10.28, add = TRUE)
divide.world("Czech Republic", "Germany", from = 10.15, to = 17.15, add = TRUE)
divide.world("Poland", "Germany", from = 17.15, to = 17.44, add = TRUE)
divide.world("Poland", "Czech Republic", from = 17.15, to = 18.25, add = TRUE)
divide.world("Austria", "Slovakia", from = 16.53, to = 17.05, add = TRUE)
divide.world("Czech Republic", "Slovakia", from = 17.05, to = 18.25, add = TRUE)
divide.world("Croatia", "Slovakia", from = 16.53, to = 17.3, add = TRUE)
divide.world("Poland", "Slovakia", from = 18.25, to = 19.7, add = TRUE)
divide.world("Hungary", "Slovakia", from = 17.3, to = 19.7, add = TRUE)
divide.world("Croatia", "Hungary", from = 17.3, to = 18.49, add = TRUE)
divide.world("Poland", "Hungary", from = 19.7, to = 24.17, add = TRUE)
divide.world("Croatia", "Bosnia and Herzegovina", from = 15.4, to = 18.31, add = TRUE)
divide.world("Bosnia and Herzegovina", "Italy", from = 15.38, to = 15.88, add = TRUE)
divide.world("Bosnia and Herzegovina", "San Marino", from = 15.38, to = 15.4, add = TRUE)
divide.world("Bosnia and Herzegovina", "Serbia", from = 18.31, to = 20.05, add = TRUE)
divide.world("Serbia", "Hungary", from = 18.49, to = 23.61, add = TRUE)
divide.world("Serbia", "Croatia", from = 18.31, to = 18.49, add = TRUE)
divide.world("Bosnia and Herzegovina", "Montenegro", from = 15.88, to = 19.99, add = TRUE)
divide.world("Montenegro", "Italy", from = 15.88, to = 16.06, add = TRUE)
divide.world("Montenegro", "Kosovo", from = 19.99, to = 20.31, add = TRUE)
divide.world("Bosnia and Herzegovina", "Kosovo", from = 19.99, to = 20.05, add = TRUE)
divide.world("Kosovo", "Serbia", from = 20.05, to = 22.21, add = TRUE)
divide.world("Montenegro", "Albania", from = 16.06, to = 20.3, add = TRUE)
divide.world("Albania", "Italy", from = 15.87, to = 16.06, add = TRUE)
divide.world("Macedonia", "Kosovo", from = 20.31, to = 22.25, add = TRUE)
divide.world("Macedonia", "Montenegro", from = 20.3, to = 20.31, add = TRUE)
divide.world("Albania", "Macedonia", from = 20.3, to = 22, add = TRUE)
divide.world("Greece", "Macedonia", from = 22, to = 23.7, add = TRUE)
divide.world("Greece", "Albania", from = 18.85, to = 22, add = TRUE)
divide.world("Bulgaria", "Macedonia", from = 22.25, to = 23.7, add = TRUE)
divide.world("Bulgaria", "Greece", from = 23.7, to = 27.7, add = TRUE)
divide.world("Bulgaria", "Kosovo", from = 22.21, to = 22.25, add = TRUE)
divide.world("Bulgaria", "Serbia", from = 22.21, to = 23.3, add = TRUE)
divide.world("Bulgaria", "Romania", from = 23.3, to = 27.85, add = TRUE)
divide.world("Serbia", "Romania", from = 23.3, to = 23.61, add = TRUE)
divide.world("Romania", "Hungary", from = 23.61, to = 23.9, add = TRUE)
divide.world("Ukraine", "Poland", from = 24.95, to = 25.7, add = TRUE)
divide.world("Romania", "Turkey", from = 27.85, to = 31.3, add = TRUE)
divide.world("Bulgaria", "Turkey", from = 27.7, to = 27.85, add = TRUE)
divide.world("Greece", "Turkey", from = 27.7, to = 28.85, add = TRUE)
divide.world("Monaco", "Andorra", from = 3.6, to = 5.6, add = TRUE)
divide.world("Andorra", "Switzerland", from = 3.1, to = 3.6, add = TRUE)
divide.world("Andorra", "France", from = -4.5, to = 3.1, add = TRUE)
divide.world("Andorra", "Spain", from = -4.5, to = 0.38, add = TRUE)
divide.world("France", "Spain", from = -6.9, to = -4.5, add = TRUE)
divide.world("United Kingdom", "Spain", from = -7.2, to = -6.9, add = TRUE)
divide.world("Portugal", "Spain", from = -10.4, to = -5.9, add = TRUE)
divide.world("United Kingdom", "Ireland", from = -7.2, to = 0.22, add = TRUE)
divide.world("Spain", "Ireland", from = -10.4, to = -7.2, add = TRUE)
divide.world("Ireland", "Portugal", from = -40, to = -10.4, add = TRUE)
divide.world("Morocco", "Portugal", from = -40, to = -8.6, add = TRUE)
divide.world("Algeria", "Andorra", from = 0.38, to = 5.6, add = TRUE)
divide.world("Algeria", "Monaco", from = 5.6, to = 6.56, add = TRUE)
divide.world("Algeria", "Spain", from = -1.28, to = 0.38, add = TRUE)
divide.world("Morocco", "Algeria", from = -0.7, to = 1, add = TRUE)
divide.world("Italy", "Tunisia", from = 11.1, to = 13.2, add = TRUE)
divide.world("Vatican", "Tunisia", from = 8.2, to = 11.1, add = TRUE)
divide.world("Monaco", "Tunisia", from = 6.56, to = 8.2, add = TRUE)
divide.world("Tunisia", "Algeria", from = 6.56, to = 6.671, add = TRUE)
divide.world("Tunisia", "Libya", from = 6.671, to = 11.9, add = TRUE)
divide.world("Algeria", "Libya", from = 3, to = 6.671, add = TRUE)
divide.world("Libya", "Greece", from = 20.7, to = 22, add = TRUE)
divide.world("Egypt", "Greece", from = 22, to = 27.5, add = TRUE)
divide.world("Egypt", "Libya", from = 20, to = 22, add = TRUE)
divide.world("Libya", "Malta", from = 11.9, to = 20.7, add = TRUE)
divide.world("Tunisia", "Malta", from = 11.9, to = 13.2, add = TRUE)
divide.world("Italy", "Malta", from = 13.2, to = 15.87, add = TRUE)
divide.world("Malta", "Albania", from = 15.87, to = 18.85, add = TRUE)
divide.world("Malta", "Greece", from = 18.85, to = 20.7, add = TRUE)
divide.world("Iceland", "Ireland", from = -40, to = -17.7, add = TRUE)
divide.world("Netherlands", "Ireland", from = 0.22, to = 0.61, add = TRUE)
divide.world("Norway", "Ireland", from = 0.58, to = 0.61, add = TRUE)
divide.world("Netherlands", "Norway", from = 0.61, to = 4.89, add = TRUE)
divide.world("Denmark", "Norway", from = 4.89, to = 14, add = TRUE)
divide.world("Denmark", "Netherlands", from = 4.89, to = 9.09, add = TRUE)
divide.world("Denmark", "Germany", from = 9.09, to = 17.44, add = TRUE)
divide.world("Denmark", "Sweden", from = 14, to = 18.4, add = TRUE)
divide.world("Denmark", "Poland", from = 17.44, to = 18.6, add = TRUE)
divide.world("Norway", "Sweden", from = 14, to = 17.2, add = TRUE)
divide.world("Lithuania", "Poland", from = 20.5, to = 24.7, add = TRUE)
divide.world("Lithuania", "Belarus", from = 24.7, to = 28.7, add = TRUE)
divide.world("Poland", "Belarus", from = 24.7, to = 25.7, add = TRUE)
divide.world("Ukraine", "Belarus", from = 25.7, to = 33.3, add = TRUE)
divide.world("Lithuania", "Latvia", from = 20.5, to = 28.7, add = TRUE)
divide.world("Poland", "Latvia", from = 18.6, to = 20.5, add = TRUE)
divide.world("Latvia", "Denmark", from = 18.4, to = 18.6, add = TRUE)
divide.world("Latvia", "Sweden", from = 18.4, to = 21.47, add = TRUE)
divide.world("Latvia", "Estonia", from = 21.47, to = 31.25, add = TRUE)
divide.world("Sweden", "Estonia", from = 21.36, to = 21.47, add = TRUE)
divide.world("Finland", "Estonia", from = 21.36, to = 32.8, add = TRUE)
divide.world("Finland", "Sweden", from = 17.2, to = 21.36, add = TRUE)
divide.world("Finland", "Norway", from = 16, to = 17.2, add = TRUE)
divide.world("Latvia", "Belarus", from = 28.7, to = 31.15, add = TRUE)
divide.world("Russia", "Belarus", from = 31.15, to = 33.3, add = TRUE)
divide.world("Russia", "Latvia", from = 31.15, to = 31.25, add = TRUE)
divide.world("Russia", "Estonia", from = 31.25, to = 32.8, add = TRUE)
divide.world("Russia", "Finland", from = 32.8, to = 60, add = TRUE)
divide.world("Russia", "Ukraine", from = 33.3, to = 41.7, add = TRUE)
divide.world("Moldova", "Romania", from = 23.9, to = 31.3, add = TRUE)
divide.world("Moldova", "Hungary", from = 23.97, to = 24.17, add = TRUE)
divide.world("Moldova", "Turkey", from = 31.3, to = 37.6, add = TRUE)
divide.world("Moldova", "Poland", from = 24.17, to = 24.95, add = TRUE)
divide.world("Moldova", "Ukraine", from = 24.95, to = 38.5, add = TRUE)
divide.world("Russia", "Kazakhstan", from = 54.05, to = 60, add = TRUE)
divide.world("Armenia", "Turkey", from = 38.62, to = 38.75, add = TRUE)
divide.world("Armenia", "Georgia", from = 38.62, to = 47.18, add = TRUE)
divide.world("Georgia", "Turkey", from = 37.6, to = 38.62, add = TRUE)
divide.world("Georgia", "Moldova", from = 37.6, to = 38.5, add = TRUE)
divide.world("Georgia", "Ukraine", from = 38.5, to = 41.7, add = TRUE)
divide.world("Georgia", "Russia", from = 41.7, to = 52.5, add = TRUE)
divide.world("Georgia", "Azerbaijan", from = 47.18, to = 52.5, add = TRUE)
divide.world("Armenia", "Azerbaijan", from = 47.18, to = 47.38, add = TRUE)
divide.world("Russia", "Azerbaijan", from = 52.5, to = 54.05, add = TRUE)
divide.world("Kazakhstan", "Azerbaijan", from = 54.05, to = 58.6, add = TRUE)
divide.world("Turkmenistan", "Azerbaijan", from = 54, to = 58.6, add = TRUE)
divide.world("Uzbekistan", "Kazakhstan", from = 59.4, to = 60, add = TRUE)
divide.world("Uzbekistan", "Turkmenistan", from = 59.4, to = 60, add = TRUE)
divide.world("Kazakhstan", "Turkmenistan", from = 58.6, to = 59.4, add = TRUE)
divide.world("Iran", "Azerbaijan", from = 47.38, to = 54, add = TRUE)
divide.world("Iran", "Turkmenistan", from = 54, to = 57.9, add = TRUE)
divide.world("Iran", "Armenia", from = 46.8, to = 47.38, add = TRUE)
divide.world("Iran", "Kuwait", from = 48.7, to = 54, add = TRUE)
divide.world("Iraq", "Kuwait", from = 41.5, to = 48.7, add = TRUE)
divide.world("Iraq", "Iran", from = 46.8, to = 48.7, add = TRUE)
divide.world("Armenia", "Iraq", from = 40.45, to = 46.8, add = TRUE)
divide.world("Syria", "Iraq", from = 40.3, to = 40.45, add = TRUE)
divide.world("Syria", "Armenia", from = 38.9, to = 40.45, add = TRUE)
divide.world("Lebanon", "Syria", from = 35.32, to = 38.9, add = TRUE)
divide.world("Lebanon", "Armenia", from = 38.75, to = 38.9, add = TRUE)
divide.world("Turkey", "Lebanon", from = 37.5, to = 38.75, add = TRUE)
divide.world("Cyprus", "Lebanon", from = 33.1, to = 37.5, add = TRUE)
divide.world("Cyprus", "Turkey", from = 28.85, to = 37.5, add = TRUE)
divide.world("Greece", "Cyprus", from = 27.5, to = 28.85, add = TRUE)
divide.world("Egypt", "Cyprus", from = 27.5, to = 32.2, add = TRUE)
divide.world("Israel", "Lebanon", from = 33.1, to = 35.225, add = TRUE)
divide.world("Israel", "Cyprus", from = 32.2, to = 33.1, add = TRUE)
divide.world("Egypt", "Israel", from = 32.2, to = 36, add = TRUE)
divide.world("Palestinian Territory", "Jordan", from = 35.23, to = 40.26, add = TRUE)
divide.world("Jordan", "Syria", from = 35.32, to = 40.3, add = TRUE)
divide.world("Jordan", "Lebanon", from = 35.22, to = 35.32, add = TRUE)
divide.world("Jordan", "Iraq", from = 40.3, to = 42, add = TRUE)
divide.world("Saudi Arabia", "Kuwait", from = 41.5, to = 48, add = TRUE)
divide.world("Saudi Arabia", "Iraq", from = 41.2, to = 41.5, add = TRUE)
divide.world("Bahrain", "Kuwait", from = 48, to = 54, add = TRUE)
divide.world("Bahrain", "Iran", from = 54, to = 57.3, add = TRUE)
divide.world("Bahrain", "Qatar", from = 50, to = 57.3, add = TRUE)
divide.world("Iran", "Qatar", from = 57.3, to = 57.9, add = TRUE)
divide.world("Faroe Islands", "Iceland", from = -17.7, to = 5, add = TRUE)
divide.world("Faroe Islands", "Norway", from = 0.58, to = 15, add = TRUE)
divide.world("Faroe Islands", "Ireland", from = -17.7, to = 0.58, add = TRUE)
divide.world("Gibraltar", "Morocco", from = -8.6, to = -0.7, add = TRUE)
divide.world("Gibraltar", "Portugal", from = -8.6, to = -5.9, add = TRUE)
divide.world("Gibraltar", "Spain", from = -5.9, to = -1.28, add = TRUE)
divide.world("Gibraltar", "Algeria", from = -1.28, to = -0.7, add = TRUE)
lines(c(35.225, 35.225), c(25, 32.83), col = "red")

points(capitals[countries, c("Longitude", "Latitude")], pch = 15, col = "blue")