countries <- row.names(capitals)

dx <- -10
dy <- -40
plot(svet, #xlim = c(-50, 0)+dx, ylim = c(0, 40)+dy,
     #xlim = c(-20, 0)+dx, ylim = c(0, 20)+dy,
     #xlim = c(-66,-65), ylim = c(13, 15),
     bg = "lightblue", col = "white", border = "lightgray", axes = TRUE,)
divide.world("Afghanistan", "India", from = 67.9, to = 69.2, add = TRUE)
divide.world("Afghanistan", "Oman", from = 61.34, to = 67.9, add = TRUE)
divide.world("Afghanistan", "Pakistan", from = 69.2, to = 71.9, add = TRUE)
divide.world("Afghanistan", "Tajikistan", from = 63.76, to = 71.9, add = TRUE)
divide.world("Afghanistan", "Turkmenistan", from = 61.34, to = 63.76, add = TRUE)
divide.world("Albania", "Greece", from = 18.85, to = 22, add = TRUE)
divide.world("Albania", "Italy", from = 15.87, to = 16.06, add = TRUE)
divide.world("Albania", "Macedonia", from = 20.3, to = 22, add = TRUE)
divide.world("Albania", "Malta", from = 15.87, to = 18.85, add = TRUE)
divide.world("Albania", "Montenegro", from = 16.06, to = 20.3, add = TRUE)
divide.world("Algeria", "Andorra", from = 0.38, to = 5.6, add = TRUE)
divide.world("Algeria", "Gibraltar", from = -1.28, to = -0.72, add = TRUE)
divide.world("Algeria", "Libya", from = 2.48, to = 6.671, add = TRUE)
divide.world("Algeria", "Monaco", from = 5.6, to = 6.56, add = TRUE)
divide.world("Algeria", "Morocco", from = -0.72, to = 2.48, add = TRUE)
divide.world("Algeria", "Spain", from = -1.28, to = 0.38, add = TRUE)
divide.world("Algeria", "Tunisia", from = 6.56, to = 6.671, add = TRUE)
divide.world("American Samoa", "French Polynesia", from = -160, to = -155.15, add = TRUE)
divide.world("American Samoa", "Marshall Islands", from = -160, to = -155.15, add = TRUE)
divide.world("American Samoa", "Niue", from = -172.6, to = -160, add = TRUE)
divide.world("American Samoa", "Samoa", from = -172.6, to = -160, add = TRUE)
divide.world("Andorra", "France", from = -4.5, to = 3.1, add = TRUE)
divide.world("Andorra", "Monaco", from = 3.6, to = 5.6, add = TRUE)
divide.world("Andorra", "Spain", from = -4.5, to = 0.38, add = TRUE)
divide.world("Andorra", "Switzerland", from = 3.1, to = 3.6, add = TRUE)
divide.world("Antigua and Barbuda", "Barbados", from = -56.1, to = -42.14, add = TRUE)
divide.world("Antigua and Barbuda", "Bermuda", from = -60.5, to = -41.92, add = TRUE)
divide.world("Antigua and Barbuda", "Cape Verde", from = -42.14, to = -41.92, add = TRUE)
divide.world("Antigua and Barbuda", "Dominica", from = -62.55, to = -56.1, add = TRUE)
divide.world("Antigua and Barbuda", "Saint Kitts and Nevis", from = -62.55, to = -60.5, add = TRUE)
divide.world("Argentina", "Chile", from = -98.1, to = -63.95, add = TRUE)
divide.world("Argentina", "New Zealand", from = -98.1, to = -96.5, add = TRUE)
divide.world("Argentina", "Paraguay", from = -63.95, to = -56.62, add = TRUE)
divide.world("Argentina", "Uruguay", from = -96.5, to = -56.62, add = TRUE)
divide.world("Armenia", "Azerbaijan", from = 47.18, to = 47.38, add = TRUE)
divide.world("Armenia", "Georgia", from = 38.62, to = 47.18, add = TRUE)
divide.world("Armenia", "Iran", from = 46.8, to = 47.38, add = TRUE)
divide.world("Armenia", "Iraq", from = 40.45, to = 46.8, add = TRUE)
divide.world("Armenia", "Lebanon", from = 38.75, to = 38.9, add = TRUE)
divide.world("Armenia", "Syria", from = 38.9, to = 40.45, add = TRUE)
divide.world("Armenia", "Turkey", from = 38.62, to = 38.75, add = TRUE)
divide.world("Australia", "East Timor", from = 111.88, to = 135.76, add = TRUE)
divide.world("Australia", "Indonesia", from = 96.15, to = 111.88, add = TRUE)
divide.world("Australia", "New Caledonia", from = 152, to = 163.3, add = TRUE)
divide.world("Australia", "New Zealand", from = 130, to = 163.3, add = TRUE)
divide.world("Australia", "Papua New Guinea", from = 135.76, to = 152, add = TRUE)
divide.world("Austria", "Croatia", from = 15.64, to = 16.53, add = TRUE)
divide.world("Austria", "Czech Republic", from = 13, to = 17.05, add = TRUE)
divide.world("Austria", "Slovakia", from = 16.53, to = 17.05, add = TRUE)
divide.world("Austria", "Slovenia", from = 13, to = 15.64, add = TRUE)
divide.world("Azerbaijan", "Georgia", from = 47.18, to = 52.5, add = TRUE)
divide.world("Azerbaijan", "Iran", from = 47.38, to = 53.9, add = TRUE)
divide.world("Azerbaijan", "Kazakhstan", from = 54.05, to = 58.6, add = TRUE)
divide.world("Azerbaijan", "Russia", from = 52.5, to = 54.05, add = TRUE)
divide.world("Azerbaijan", "Turkmenistan", from = 53.9, to = 58.6, add = TRUE)
divide.world("Bahamas", "Bermuda", from = -73.6, to = -69.1, add = TRUE)
divide.world("Bahamas", "Cuba", from = -83.7, to = -78.7, add = TRUE)
divide.world("Bahamas", "Dominican Republic", from = -71.055, to = -69.1, add = TRUE)
divide.world("Bahamas", "Haiti", from = -75.03, to = -71.055, add = TRUE)
divide.world("Bahamas", "Jamaica", from = -78.7, to = -75.03, add = TRUE)
divide.world("Bahamas", "United States", from = -83.7, to = -73.6, add = TRUE)
divide.world("Bahrain", "Iran", from = 54, to = 55.6, add = TRUE)
divide.world("Bahrain", "Kuwait", from = 47.9, to = 54, add = TRUE)
divide.world("Bahrain", "Qatar", from = 49.22, to = 54.1, add = TRUE)
divide.world("Bahrain", "Saudi Arabia", from = 47.9, to = 49.22, add = TRUE)
divide.world("Bahrain", "United Arab Emirates", from = 54.1, to = 55.6, add = TRUE)
divide.world("Bangladesh", "Bhutan", from = 87.32, to = 97.4, add = TRUE)
divide.world("Bangladesh", "Myanmar", from = 87.38, to = 97.4, add = TRUE)
divide.world("Bangladesh", "Nepal", from = 80.8, to = 87.32, add = TRUE)
divide.world("Bangladesh", "Sri Lanka", from = 80.8, to = 87.38, add = TRUE)
divide.world("Barbados", "Cape Verde", from = -42.14, to = -41.954, add = TRUE)
divide.world("Barbados", "Dominica", from = -59.2, to = -56.1, add = TRUE)
divide.world("Barbados", "French Guiana", from = -51.13, to = -41.954, add = TRUE)
divide.world("Barbados", "Grenada", from = -60.46, to = -60.2, add = TRUE)
divide.world("Barbados", "Guyana", from = -58.2, to = -55.27, add = TRUE)
divide.world("Barbados", "Saint Lucia", from = -60.41, to = -59.2, add = TRUE)
divide.world("Barbados", "Saint Vincent and the Grenadines", from = -60.46, to = -60.41, add = TRUE)
divide.world("Barbados", "Suriname", from = -55.27, to = -51.13, add = TRUE)
divide.world("Barbados", "Trinidad and Tobago", from = -60.2, to = -58.2, add = TRUE)
divide.world("Belarus", "Latvia", from = 28.7, to = 31.15, add = TRUE)
divide.world("Belarus", "Lithuania", from = 24.7, to = 28.7, add = TRUE)
divide.world("Belarus", "Poland", from = 24.7, to = 25.7, add = TRUE)
divide.world("Belarus", "Russia", from = 31.15, to = 33.3, add = TRUE)
divide.world("Belarus", "Ukraine", from = 25.7, to = 33.3, add = TRUE)
divide.world("Belgium", "France", from = 1.85, to = 4.1, add = TRUE)
divide.world("Belgium", "Luxembourg", from = 4.1, to = 7, add = TRUE)
divide.world("Belgium", "Netherlands", from = 2.4, to = 7, add = TRUE)
divide.world("Belgium", "United Kingdom", from = 1.85, to = 2.4, add = TRUE)
divide.world("Belize", "Cuba", from = -92, to = -83.1, add = TRUE)
divide.world("Belize", "El Salvador", from = -88.9, to = -88.5, add = TRUE)
divide.world("Belize", "Guatemala", from = -93.9, to = -88.9, add = TRUE)
divide.world("Belize", "Honduras", from = -88.5, to = -83.1, add = TRUE)
divide.world("Belize", "Mexico", from = -93.9, to = -92, add = TRUE)
divide.world("Bermuda", "Canada", from = -66.5, to = -49.8, add = TRUE)
divide.world("Bermuda", "Cape Verde", from = -41.92, to = -38.2, add = TRUE)
divide.world("Bermuda", "Dominican Republic", from = -69.1, to = -68, add = TRUE)
divide.world("Bermuda", "Greenland", from = -49.8, to = -38.9, add = TRUE)
divide.world("Bermuda", "Portugal", from = -38.9, to = -37.7, add = TRUE)
divide.world("Bermuda", "Puerto Rico", from = -68, to = -61.5, add = TRUE)
divide.world("Bermuda", "Saint Kitts and Nevis", from = -61.5, to = -60.5, add = TRUE)
divide.world("Bermuda", "United States", from = -73.6, to = -66.5, add = TRUE)
divide.world("Bermuda", "Western Sahara", from = -38.2, to = -37.7, add = TRUE)
divide.world("Bhutan", "China", from = 101.07, to = 102.7, add = TRUE)
divide.world("Bhutan", "Kyrgyzstan", from = 88.33, to = 91.85, add = TRUE)
divide.world("Bhutan", "Mongolia", from = 91.85, to = 101.07, add = TRUE)
divide.world("Bhutan", "Myanmar", from = 97.4, to = 99.76, add = TRUE)
divide.world("Bhutan", "Nepal", from = 87.32, to = 88.33, add = TRUE)
divide.world("Bhutan", "Vietnam", from = 99.76, to = 102.7, add = TRUE)
divide.world("Bolivia", "Brazil", from = -58.55, to = -56.65, add = TRUE)
divide.world("Bolivia", "Chile", from = -76.5, to = -66.1, add = TRUE)
divide.world("Bolivia", "Colombia", from = -65, to = -64.6, add = TRUE)
divide.world("Bolivia", "Guyana", from = -64.6, to = -60.65, add = TRUE)
divide.world("Bolivia", "Paraguay", from = -66.1, to = -56.65, add = TRUE)
divide.world("Bolivia", "Peru", from = -76.5, to = -65, add = TRUE)
divide.world("Bolivia", "Suriname", from = -60.65, to = -58.55, add = TRUE)
divide.world("Bosnia and Herzegovina", "Croatia", from = 15.4, to = 18.31, add = TRUE)
divide.world("Bosnia and Herzegovina", "Italy", from = 15.38, to = 15.88, add = TRUE)
divide.world("Bosnia and Herzegovina", "Kosovo", from = 19.99, to = 20.05, add = TRUE)
divide.world("Bosnia and Herzegovina", "Montenegro", from = 15.88, to = 19.99, add = TRUE)
divide.world("Bosnia and Herzegovina", "San Marino", from = 15.38, to = 15.4, add = TRUE)
divide.world("Bosnia and Herzegovina", "Serbia", from = 18.31, to = 20.05, add = TRUE)
divide.world("Brazil", "French Guiana", from = -57.87, to = -33.86, add = TRUE)
divide.world("Brazil", "Paraguay", from = -56.65, to = -43.72, add = TRUE)
divide.world("Brazil", "Suriname", from = -58.55, to = -57.87, add = TRUE)
divide.world("Brazil", "Uruguay", from = -43.72, to = -30, add = TRUE)
divide.world("Brunei", "Cambodia", from = 108.45, to = 113, add = TRUE)
divide.world("Brunei", "East Timor", from = 116.55, to = 125.3, add = TRUE)
divide.world("Brunei", "Indonesia", from = 110.55, to = 116.55, add = TRUE)
divide.world("Brunei", "Palau", from = 124.88, to = 125.3, add = TRUE)
divide.world("Brunei", "Philippines", from = 113, to = 124.88, add = TRUE)
divide.world("Brunei", "Singapore", from = 108.45, to = 110.55, add = TRUE)
divide.world("Bulgaria", "Greece", from = 23.7, to = 27.7, add = TRUE)
divide.world("Bulgaria", "Kosovo", from = 22.21, to = 22.25, add = TRUE)
divide.world("Bulgaria", "Macedonia", from = 22.25, to = 23.7, add = TRUE)
divide.world("Bulgaria", "Romania", from = 23.3, to = 27.85, add = TRUE)
divide.world("Bulgaria", "Serbia", from = 22.21, to = 23.3, add = TRUE)
divide.world("Bulgaria", "Turkey", from = 27.7, to = 27.85, add = TRUE)
divide.world("Cambodia", "Laos", from = 103.8, to = 107.8, add = TRUE)
divide.world("Cambodia", "Macao", from = 110.69, to = 112.7, add = TRUE)
divide.world("Cambodia", "Malaysia", from = 100.5, to = 106.2, add = TRUE)
divide.world("Cambodia", "Philippines", from = 112.7, to = 113, add = TRUE)
divide.world("Cambodia", "Singapore", from = 106.2, to = 108.45, add = TRUE)
divide.world("Cambodia", "Thailand", from = 100.5, to = 103.8, add = TRUE)
divide.world("Cambodia", "Vietnam", from = 107.8, to = 110.69, add = TRUE)
divide.world("Canada", "Greenland", from = -153.2, to = -49.8, add = TRUE)
divide.world("Canada", "Japan", from = -153.2, to = -152.2, add = TRUE)
divide.world("Canada", "Marshall Islands", from = -152.2, to = -151.8, add = TRUE)
divide.world("Canada", "Mexico", from = -151.8, to = -107.2, add = TRUE)
divide.world("Canada", "United States", from = -107.2, to = -66.5, add = TRUE)
divide.world("Cape Verde", "French Guiana", from = -41.954, to = -33.86, add = TRUE)
divide.world("Cape Verde", "Mauritania", from = -23.7, to = -18, add = TRUE)
divide.world("Cape Verde", "Western Sahara", from = -38.2, to = -23.7, add = TRUE)
divide.world("Chile", "French Polynesia", from = -123.3, to = -111.92, add = TRUE)
divide.world("Chile", "New Zealand", from = -123.3, to = -98.1, add = TRUE)
divide.world("Chile", "Paraguay", from = -66.1, to = -63.95, add = TRUE)
divide.world("Chile", "Peru", from = -111.92, to = -76.5, add = TRUE)
divide.world("China", "Hong Kong", from = 112.18, to = 114.2, add = TRUE)
divide.world("China", "Macao", from = 107.75, to = 112.18, add = TRUE)
divide.world("China", "Mongolia", from = 101.07, to = 123, add = TRUE)
divide.world("China", "North Korea", from = 120.41, to = 123, add = TRUE)
divide.world("China", "South Korea", from = 119.7, to = 120.41, add = TRUE)
divide.world("China", "Taiwan", from = 114.2, to = 119.7, add = TRUE)
divide.world("China", "Vietnam", from = 102.7, to = 107.75, add = TRUE)
divide.world("Colombia", "Ecuador", from = -78.75, to = -68.5, add = TRUE)
divide.world("Colombia", "Guyana", from = -65.56, to = -64.6, add = TRUE)
divide.world("Colombia", "Panama", from = -78.75, to = -73.35, add = TRUE)
divide.world("Colombia", "Peru", from = -68.5, to = -65, add = TRUE)
divide.world("Colombia", "Venezuela", from = -73.35, to = -65.56, add = TRUE)
divide.world("Costa Rica", "Ecuador", from = -98.9, to = -82.96, add = TRUE)
divide.world("Costa Rica", "El Salvador", from = -98.9, to = -92.7, add = TRUE)
divide.world("Costa Rica", "Jamaica", from = -81.3, to = -80.75, add = TRUE)
divide.world("Costa Rica", "Nicaragua", from = -92.7, to = -81.3, add = TRUE)
divide.world("Costa Rica", "Panama", from = -82.96, to = -80.75, add = TRUE)
divide.world("Croatia", "Hungary", from = 17.3, to = 18.49, add = TRUE)
divide.world("Croatia", "San Marino", from = 14.75, to = 15.4, add = TRUE)
divide.world("Croatia", "Serbia", from = 18.31, to = 18.49, add = TRUE)
divide.world("Croatia", "Slovakia", from = 16.53, to = 17.3, add = TRUE)
divide.world("Croatia", "Slovenia", from = 14.75, to = 15.64, add = TRUE)
divide.world("Cuba", "Honduras", from = -83.1, to = -82.6, add = TRUE)
divide.world("Cuba", "Jamaica", from = -82.6, to = -78.7, add = TRUE)
divide.world("Cuba", "Mexico", from = -94.3, to = -92, add = TRUE)
divide.world("Cuba", "United States", from = -94.3, to = -83.7, add = TRUE)
divide.world("Cyprus", "Egypt", from = 27.5, to = 32.2, add = TRUE)
divide.world("Cyprus", "Greece", from = 27.5, to = 28.85, add = TRUE)
divide.world("Cyprus", "Israel", from = 32.2, to = 33.1, add = TRUE)
divide.world("Cyprus", "Lebanon", from = 33.1, to = 37.5, add = TRUE)
divide.world("Cyprus", "Turkey", from = 28.85, to = 37.5, add = TRUE)
divide.world("Czech Republic", "Germany", from = 10.15, to = 17.15, add = TRUE)
divide.world("Czech Republic", "Liechtenstein", from = 10.28, to = 12.7, add = TRUE)
divide.world("Czech Republic", "Luxembourg", from = 10.15, to = 10.28, add = TRUE)
divide.world("Czech Republic", "Poland", from = 17.15, to = 18.25, add = TRUE)
divide.world("Czech Republic", "Slovakia", from = 17.05, to = 18.25, add = TRUE)
divide.world("Czech Republic", "Slovenia", from = 12.7, to = 13, add = TRUE)
divide.world("Denmark", "Germany", from = 9.09, to = 17.44, add = TRUE)
divide.world("Denmark", "Latvia", from = 18.4, to = 18.6, add = TRUE)
divide.world("Denmark", "Netherlands", from = 4.89, to = 9.09, add = TRUE)
divide.world("Denmark", "Norway", from = 4.89, to = 14, add = TRUE)
divide.world("Denmark", "Poland", from = 17.44, to = 18.6, add = TRUE)
divide.world("Denmark", "Sweden", from = 14, to = 18.4, add = TRUE)
divide.world("Djibouti", "Eritrea", from = 40, to = 41.575, add = TRUE)
divide.world("Djibouti", "Somalia", from = 45, to = 57.05, add = TRUE)
divide.world("Djibouti", "Yemen", from = 41.575, to = 57.05, add = TRUE)
divide.world("Dominica", "Grenada", from = -65.2, to = -64.5, add = TRUE)
divide.world("Dominica", "Saint Kitts and Nevis", from = -65.4, to = -62.55, add = TRUE)
divide.world("Dominica", "Saint Lucia", from = -63.3, to = -59.2, add = TRUE)
divide.world("Dominica", "Saint Vincent and the Grenadines", from = -64.5, to = -63.3, add = TRUE)
divide.world("Dominica", "Venezuela", from = -65.4, to = -65.2, add = TRUE)
divide.world("Dominican Republic", "Haiti", from = -71.26, to = -71.055, add = TRUE)
divide.world("Dominican Republic", "Puerto Rico", from = -68.082, to = -67.986, add = TRUE)
divide.world("Dominican Republic", "Venezuela", from = -71.26, to = -68.082, add = TRUE)
divide.world("East Timor", "Indonesia", from = 111.88, to = 116.55, add = TRUE)
divide.world("East Timor", "Palau", from = 125.3, to = 136.57, add = TRUE)
divide.world("East Timor", "Papua New Guinea", from = 135.76, to = 136.57, add = TRUE)
divide.world("Ecuador", "El Salvador", from = -104, to = -98.9, add = TRUE)
divide.world("Ecuador", "Panama", from = -82.96, to = -78.75, add = TRUE)
divide.world("Ecuador", "Peru", from = -104, to = -68.5, add = TRUE)
divide.world("Egypt", "Eritrea", from = 36.026, to = 37.2, add = TRUE)
divide.world("Egypt", "Greece", from = 22, to = 27.5, add = TRUE)
divide.world("Egypt", "Israel", from = 32.2, to = 35.225, add = TRUE)
divide.world("Egypt", "Libya", from = 20, to = 22, add = TRUE)
divide.world("Egypt", "Palestinian Territory", from = 35.225, to = 37.2, add = TRUE)
divide.world("Egypt", "Sudan", from = 32, to = 36.026, add = TRUE)
divide.world("El Salvador", "Guatemala", from = -107.4, to = -88.9, add = TRUE)
divide.world("El Salvador", "Honduras", from = -88.5, to = -87.9, add = TRUE)
divide.world("El Salvador", "Nicaragua", from = -92.7, to = -87.9, add = TRUE)
divide.world("El Salvador", "Peru", from = -107.4, to = -104, add = TRUE)
divide.world("Eritrea", "Palestinian Territory", from = 37.2, to = 37.6, add = TRUE)
divide.world("Eritrea", "Saudi Arabia", from = 37.6, to = 41.547, add = TRUE)
divide.world("Eritrea", "Sudan", from = 35.7, to = 36.026, add = TRUE)
divide.world("Eritrea", "Yemen", from = 41.547, to = 41.575, add = TRUE)
divide.world("Estonia", "Finland", from = 21.36, to = 32.8, add = TRUE)
divide.world("Estonia", "Latvia", from = 21.47, to = 31.25, add = TRUE)
divide.world("Estonia", "Russia", from = 31.25, to = 32.8, add = TRUE)
divide.world("Estonia", "Sweden", from = 21.36, to = 21.47, add = TRUE)
divide.world("Faroe Islands", "Iceland", from = -17.7, to = 23.2, add = TRUE)
divide.world("Faroe Islands", "Ireland", from = -17.7, to = 0.58, add = TRUE)
divide.world("Faroe Islands", "Finland", from = 15.77, to = 23.2, add = TRUE)
divide.world("Faroe Islands", "Norway", from = 0.58, to = 15.77, add = TRUE)
divide.world("Fiji", "New Caledonia", from = 173.19, to = 176.2, add = TRUE)
divide.world("Fiji", "Samoa", from = -177.8, to = -176.6, add = TRUE)
divide.world("Fiji", "Tonga", from = 176.2, to = 180, add = TRUE)
divide.world("Fiji", "Tonga", from = -180, to = -176.6, add = TRUE)
divide.world("Fiji", "Tuvalu", from = 173.6, to = 180, add = TRUE)
divide.world("Fiji", "Tuvalu", from = -180, to = -177.8, add = TRUE)
divide.world("Fiji", "Vanuatu", from = 173.19, to = 173.6, add = TRUE)
divide.world("Finland", "Iceland", from = 23.2, to = 140.9, add = TRUE)
divide.world("Finland", "Kazakhstan", from = 68.3, to = 111.5, add = TRUE)
divide.world("Finland", "Mongolia", from = 111.5, to = 140.9, add = TRUE)
divide.world("Finland", "Norway", from = 15.77, to = 17.2, add = TRUE)
divide.world("Finland", "Russia", from = 32.8, to = 68.3, add = TRUE)
divide.world("Finland", "Sweden", from = 17.2, to = 21.36, add = TRUE)
divide.world("France", "Luxembourg", from = 4.1, to = 4.88, add = TRUE)
divide.world("France", "Spain", from = -6.9, to = -4.5, add = TRUE)
divide.world("France", "Switzerland", from = 3.1, to = 4.88, add = TRUE)
divide.world("France", "United Kingdom", from = -6.9, to = 1.85, add = TRUE)
divide.world("French Guiana", "Suriname", from = -57.87, to = -51.13, add = TRUE)
divide.world("French Polynesia", "Marshall Islands", from = -155.15, to = -146.8, add = TRUE)
divide.world("French Polynesia", "Mexico", from = -146.8, to = -113.2, add = TRUE)
divide.world("French Polynesia", "New Zealand", from = -157.81, to = -123.3, add = TRUE)
divide.world("French Polynesia", "Niue", from = -160, to = -157.81, add = TRUE)
divide.world("French Polynesia", "Peru", from = -113.2, to = -111.92, add = TRUE)
divide.world("Georgia", "Moldova", from = 37.6, to = 38.5, add = TRUE)
divide.world("Georgia", "Russia", from = 41.7, to = 52.5, add = TRUE)
divide.world("Georgia", "Turkey", from = 37.6, to = 38.62, add = TRUE)
divide.world("Georgia", "Ukraine", from = 38.5, to = 41.7, add = TRUE)
divide.world("Germany", "Luxembourg", from = 9.19, to = 10.15, add = TRUE)
divide.world("Germany", "Netherlands", from = 9.09, to = 9.19, add = TRUE)
divide.world("Germany", "Poland", from = 17.15, to = 17.44, add = TRUE)
divide.world("Gibraltar", "Morocco", from = -8.6, to = -0.72, add = TRUE)
divide.world("Gibraltar", "Portugal", from = -8.6, to = -5.9, add = TRUE)
divide.world("Gibraltar", "Spain", from = -5.9, to = -1.28, add = TRUE)
divide.world("Greece", "Libya", from = 20.7, to = 22, add = TRUE)
divide.world("Greece", "Macedonia", from = 22, to = 23.7, add = TRUE)
divide.world("Greece", "Malta", from = 18.85, to = 20.7, add = TRUE)
divide.world("Greece", "Turkey", from = 27.7, to = 28.85, add = TRUE)
divide.world("Greenland", "Iceland", from = -36.889, to = 142.56, add = TRUE)
divide.world("Greenland", "Japan", from = -177.81, to = -153.2, add = TRUE)
divide.world("Greenland", "Mongolia", from = 142.56, to = 180, add = TRUE)
divide.world("Greenland", "Mongolia", from = -180, to = -177.81, add = TRUE)
divide.world("Greenland", "Portugal", from = -38.9, to = -36.889, add = TRUE)
divide.world("Grenada", "Saint Vincent and the Grenadines", from = -64.5, to = -60.46, add = TRUE)
divide.world("Grenada", "Trinidad and Tobago", from = -64.21, to = -60.2, add = TRUE)
divide.world("Grenada", "Venezuela", from = -65.2, to = -64.21, add = TRUE)
divide.world("Guam", "Japan", from = 135.6, to = 160.7, add = TRUE)
divide.world("Guam", "Micronesia", from = 147.5, to = 160.7, add = TRUE)
divide.world("Guam", "Palau", from = 133.65, to = 144.8, add = TRUE)
divide.world("Guam", "Papua New Guinea", from = 144.8, to = 147.5, add = TRUE)
divide.world("Guam", "Taiwan", from = 133.65, to = 135.6, add = TRUE)
divide.world("Guatemala", "Mexico", from = -111, to = -93.9, add = TRUE)
divide.world("Guatemala", "Peru", from = -111, to = -107.4, add = TRUE)
divide.world("Guyana", "Suriname", from = -60.65, to = -55.27, add = TRUE)
divide.world("Guyana", "Trinidad and Tobago", from = -64.013, to = -58.2, add = TRUE)
divide.world("Guyana", "Venezuela", from = -65.56, to = -64.013, add = TRUE)
divide.world("Haiti", "Jamaica", from = -75.03, to = -73.77, add = TRUE)
divide.world("Haiti", "Panama", from = -73.77, to = -73.48, add = TRUE)
divide.world("Haiti", "Venezuela", from = -73.48, to = -71.26, add = TRUE)
divide.world("Honduras", "Jamaica", from = -82.6, to = -81.7, add = TRUE)
divide.world("Honduras", "Nicaragua", from = -87.9, to = -81.7, add = TRUE)
divide.world("Hong Kong", "Macao", from = 112.18, to = 114.85, add = TRUE)
divide.world("Hong Kong", "Philippines", from = 114.85, to = 119.45, add = TRUE)
divide.world("Hong Kong", "Taiwan", from = 114.2, to = 119.45, add = TRUE)
divide.world("Hungary", "Moldova", from = 23.97, to = 24.17, add = TRUE)
divide.world("Hungary", "Poland", from = 19.7, to = 24.17, add = TRUE)
divide.world("Hungary", "Romania", from = 23.61, to = 23.9, add = TRUE)
divide.world("Hungary", "Serbia", from = 18.49, to = 23.61, add = TRUE)
divide.world("Hungary", "Slovakia", from = 17.3, to = 19.7, add = TRUE)
divide.world("Iceland", "Ireland", from = -35, to = -17.7, add = TRUE)
divide.world("Iceland", "Mongolia", from = 140.9, to = 142.56, add = TRUE)
divide.world("Iceland", "Portugal", from = -36.9, to = -35, add = TRUE)
divide.world("India", "Maldives", from = 70.66, to = 71.5, add = TRUE)
divide.world("India", "Nepal", from = 79.87, to = 82.4, add = TRUE)
divide.world("India", "Oman", from = 67.9, to = 70.66, add = TRUE)
divide.world("India", "Pakistan", from = 69.2, to = 82.4, add = TRUE)
divide.world("India", "Sri Lanka", from = 71.5, to = 79.87, add = TRUE)
divide.world("Indonesia", "Malaysia", from = 88.1, to = 95.35, add = TRUE)
divide.world("Indonesia", "Maldives", from = 84.3, to = 85.65, add = TRUE)
divide.world("Indonesia", "Mauritius", from = 84.3, to = 96.15, add = TRUE)
divide.world("Indonesia", "Singapore", from = 95.35, to = 110.55, add = TRUE)
divide.world("Indonesia", "Sri Lanka", from = 85.65, to = 88.1, add = TRUE)
divide.world("Iran", "Iraq", from = 46.8, to = 48.7, add = TRUE)
divide.world("Iran", "Kuwait", from = 48.7, to = 54, add = TRUE)
divide.world("Iran", "Turkmenistan", from = 53.9, to = 57.65, add = TRUE)
divide.world("Iran", "United Arab Emirates", from = 55.6, to = 57.65, add = TRUE)
divide.world("Iraq", "Jordan", from = 40.3, to = 41.17, add = TRUE)
divide.world("Iraq", "Kuwait", from = 41.5, to = 48.7, add = TRUE)
divide.world("Iraq", "Saudi Arabia", from = 41.17, to = 41.5, add = TRUE)
divide.world("Iraq", "Syria", from = 40.3, to = 40.45, add = TRUE)
divide.world("Ireland", "Netherlands", from = 0.22, to = 0.61, add = TRUE)
divide.world("Ireland", "Norway", from = 0.58, to = 0.61, add = TRUE)
divide.world("Ireland", "Portugal", from = -35, to = -10.4, add = TRUE)
divide.world("Ireland", "Spain", from = -10.4, to = -7.2, add = TRUE)
divide.world("Ireland", "United Kingdom", from = -7.2, to = 0.22, add = TRUE)
divide.world("Israel", "Lebanon", from = 33.1, to = 35.225, add = TRUE)
divide.world("Italy", "Malta", from = 13.2, to = 15.87, add = TRUE)
divide.world("Italy", "Montenegro", from = 15.88, to = 16.06, add = TRUE)
divide.world("Italy", "San Marino", from = 13.1, to = 15.38, add = TRUE)
divide.world("Italy", "Tunisia", from = 11.1, to = 13.2, add = TRUE)
divide.world("Italy", "Vatican", from = 11.1, to = 13.1, add = TRUE)
divide.world("Jamaica", "Nicaragua", from = -81.7, to = -81.3, add = TRUE)
divide.world("Jamaica", "Panama", from = -80.75, to = -73.77, add = TRUE)
divide.world("Japan", "Marshall Islands", from = 164.462, to = 180, add = TRUE)
divide.world("Japan", "Marshall Islands", from = -180, to = -152.2, add = TRUE)
divide.world("Japan", "Micronesia", from = 160.7, to = 164.462, add = TRUE)
divide.world("Japan", "Mongolia", from = 149.7, to = 180, add = TRUE)
divide.world("Japan", "Mongolia", from = -180, to = -177.81, add = TRUE)
divide.world("Japan", "North Korea", from = 134.74, to = 149.7, add = TRUE)
divide.world("Japan", "South Korea", from = 131.7, to = 134.74, add = TRUE)
divide.world("Japan", "Taiwan", from = 131.7, to = 135.6, add = TRUE)
divide.world("Jordan", "Lebanon", from = 35.22, to = 35.32, add = TRUE)
divide.world("Jordan", "Palestinian Territory", from = 35.23, to = 38.1, add = TRUE)
divide.world("Jordan", "Saudi Arabia", from = 38.1, to = 41.17, add = TRUE)
divide.world("Jordan", "Syria", from = 35.32, to = 40.3, add = TRUE)
divide.world("Kazakhstan", "Kyrgyzstan", from = 69.4, to = 89.25, add = TRUE)
divide.world("Kazakhstan", "Mongolia", from = 89.25, to = 111.5, add = TRUE)
divide.world("Kazakhstan", "Russia", from = 54.05, to = 68.3, add = TRUE)
divide.world("Kazakhstan", "Turkmenistan", from = 58.6, to = 59.4, add = TRUE)
divide.world("Kazakhstan", "Uzbekistan", from = 59.4, to = 69.4, add = TRUE)
divide.world("Kiribati", "Marshall Islands", from = 169.05, to = 180, add = TRUE)
divide.world("Kiribati", "Marshall Islands", from = -180, to = -162.5, add = TRUE)
divide.world("Kiribati", "Nauru", from = 169.05, to = 172, add = TRUE)
divide.world("Kiribati", "Samoa", from = -164.8, to = -162.5, add = TRUE)
divide.world("Kiribati", "Tuvalu", from = 172, to = 180, add = TRUE)
divide.world("Kiribati", "Tuvalu", from = -180, to = -164.8, add = TRUE)
divide.world("Kosovo", "Macedonia", from = 20.31, to = 22.25, add = TRUE)
divide.world("Kosovo", "Montenegro", from = 19.99, to = 20.31, add = TRUE)
divide.world("Kosovo", "Serbia", from = 20.05, to = 22.21, add = TRUE)
divide.world("Kuwait", "Saudi Arabia", from = 41.5, to = 47.9, add = TRUE)
divide.world("Kyrgyzstan", "Mongolia", from = 89.25, to = 91.85, add = TRUE)
divide.world("Kyrgyzstan", "Nepal", from = 83.7, to = 88.33, add = TRUE)
divide.world("Kyrgyzstan", "Pakistan", from = 74.7, to = 83.7, add = TRUE)
divide.world("Kyrgyzstan", "Tajikistan", from = 73.3, to = 74.7, add = TRUE)
divide.world("Kyrgyzstan", "Uzbekistan", from = 69.4, to = 73.3, add = TRUE)
divide.world("Laos", "Myanmar", from = 98.82, to = 100.61, add = TRUE)
divide.world("Laos", "Thailand", from = 98.82, to = 103.8, add = TRUE)
divide.world("Laos", "Vietnam", from = 100.61, to = 107.8, add = TRUE)
divide.world("Latvia", "Lithuania", from = 20.5, to = 28.7, add = TRUE)
divide.world("Latvia", "Poland", from = 18.6, to = 20.5, add = TRUE)
divide.world("Latvia", "Russia", from = 31.15, to = 31.25, add = TRUE)
divide.world("Latvia", "Sweden", from = 18.4, to = 21.47, add = TRUE)
divide.world("Lebanon", "Syria", from = 35.32, to = 38.9, add = TRUE)
divide.world("Lebanon", "Turkey", from = 37.5, to = 38.75, add = TRUE)
divide.world("Libya", "Malta", from = 11.9, to = 20.7, add = TRUE)
divide.world("Libya", "Morocco", from = 2.3, to = 2.48, add = TRUE)
divide.world("Libya", "Tunisia", from = 6.671, to = 11.9, add = TRUE)
divide.world("Liechtenstein", "Luxembourg", from = 8.18, to = 10.28, add = TRUE)
divide.world("Liechtenstein", "Monaco", from = 8.81, to = 9.84, add = TRUE)
divide.world("Liechtenstein", "San Marino", from = 9.84, to = 11.7, add = TRUE)
divide.world("Liechtenstein", "Slovenia", from = 11.7, to = 12.7, add = TRUE)
divide.world("Liechtenstein", "Switzerland", from = 8.18, to = 8.81, add = TRUE)
divide.world("Lithuania", "Poland", from = 20.5, to = 24.7, add = TRUE)
divide.world("Luxembourg", "Netherlands", from = 7, to = 9.19, add = TRUE)
divide.world("Luxembourg", "Switzerland", from = 4.88, to = 8.18, add = TRUE)
divide.world("Macao", "Philippines", from = 112.7, to = 114.85, add = TRUE)
divide.world("Macao", "Vietnam", from = 107.75, to = 110.69, add = TRUE)
divide.world("Macedonia", "Montenegro", from = 20.3, to = 20.31, add = TRUE)
divide.world("Malaysia", "Singapore", from = 95.35, to = 106.2, add = TRUE)
divide.world("Malaysia", "Sri Lanka", from = 88.1, to = 91.18, add = TRUE)
divide.world("Malaysia", "Thailand", from = 91.18, to = 100.5, add = TRUE)
divide.world("Maldives", "Mauritius", from = 69.5, to = 84.3, add = TRUE)
divide.world("Maldives", "Oman", from = 59.85, to = 70.66, add = TRUE)
divide.world("Maldives", "Seychelles", from = 59.85, to = 69.5, add = TRUE)
divide.world("Maldives", "Sri Lanka", from = 71.5, to = 85.65, add = TRUE)
divide.world("Malta", "Tunisia", from = 11.9, to = 13.2, add = TRUE)
divide.world("Marshall Islands", "Nauru", from = 164.785, to = 169.05, add = TRUE)
divide.world("Marshall Islands", "Micronesia", from = 164.462, to = 164.785, add = TRUE)
divide.world("Marshall Islands", "Mexico", from = -151.8, to = -146.8, add = TRUE)
divide.world("Marshall Islands", "Samoa", from = -162.5, to = -160, add = TRUE)
divide.world("Mauritania", "Western Sahara", from = -23.7, to = -10, add = TRUE)
divide.world("Mexico", "Peru", from = -113.2, to = -111, add = TRUE)
divide.world("Mexico", "United States", from = -107.2, to = -94.3, add = TRUE)
divide.world("Micronesia", "Nauru", from = 158.7, to = 164.785, add = TRUE)
divide.world("Micronesia", "Papua New Guinea", from = 147.5, to = 153.559, add = TRUE)
divide.world("Micronesia", "Solomon Islands", from = 153.559, to = 158.7, add = TRUE)
divide.world("Moldova", "Poland", from = 24.17, to = 24.95, add = TRUE)
divide.world("Moldova", "Romania", from = 23.9, to = 31.3, add = TRUE)
divide.world("Moldova", "Turkey", from = 31.3, to = 37.6, add = TRUE)
divide.world("Moldova", "Ukraine", from = 24.95, to = 38.5, add = TRUE)
divide.world("Monaco", "San Marino", from = 9.84, to = 10.01, add = TRUE)
divide.world("Monaco", "Switzerland", from = 3.6, to = 8.81, add = TRUE)
divide.world("Monaco", "Tunisia", from = 6.56, to = 8.2, add = TRUE)
divide.world("Monaco", "Vatican", from = 8.2, to = 10.01, add = TRUE)
divide.world("Mongolia", "North Korea", from = 123, to = 149.7, add = TRUE)
divide.world("Morocco", "Portugal", from = -15, to = -8.6, add = TRUE)
divide.world("Morocco", "Western Sahara", from = -15, to = 2.3, add = TRUE)
divide.world("Myanmar", "Sri Lanka", from = 87.38, to = 90, add = TRUE)
divide.world("Myanmar", "Thailand", from = 90, to = 98.82, add = TRUE)
divide.world("Myanmar", "Vietnam", from = 99.76, to = 100.61, add = TRUE)
divide.world("Nauru", "Solomon Islands", from = 158.7, to = 168.8, add = TRUE)
divide.world("Nauru", "Tuvalu", from = 170.1, to = 172, add = TRUE)
divide.world("Nauru", "Vanuatu", from = 168.8, to = 170.1, add = TRUE)
divide.world("Nepal", "Pakistan", from = 82.4, to = 83.7, add = TRUE)
divide.world("Nepal", "Sri Lanka", from = 79.87, to = 80.8, add = TRUE)
divide.world("New Caledonia", "New Zealand", from = 163.3, to = 176.28, add = TRUE)
divide.world("New Caledonia", "Papua New Guinea", from = 152, to = 153.574, add = TRUE)
divide.world("New Caledonia", "Solomon Islands", from = 153.574, to = 160.1, add = TRUE)
divide.world("New Caledonia", "Tonga", from = 176.2, to = 176.28, add = TRUE)
divide.world("New Caledonia", "Vanuatu", from = 160.1, to = 173.19, add = TRUE)
divide.world("New Zealand", "Niue", from = -164.6, to = -157.81, add = TRUE)
divide.world("New Zealand", "Tonga", from = 176.28, to = 180, add = TRUE)
divide.world("New Zealand", "Tonga", from = -180, to = -164.6, add = TRUE)
divide.world("Netherlands", "Norway", from = 0.61, to = 4.89, add = TRUE)
divide.world("Netherlands", "United Kingdom", from = 0.22, to = 2.4, add = TRUE)
divide.world("Niue", "Samoa", from = -173.78, to = -172.6, add = TRUE)
divide.world("Niue", "Tonga", from = -173.78, to = -164.6, add = TRUE)
divide.world("North Korea", "South Korea", from = 120.41, to = 134.74, add = TRUE)
divide.world("Norway", "Sweden", from = 14, to = 17.2, add = TRUE)
divide.world("Oman", "Seychelles", from = 57.55, to = 59.85, add = TRUE)
divide.world("Oman", "Somalia", from = 57.4, to = 57.55, add = TRUE)
divide.world("Oman", "Turkmenistan", from = 58.24, to = 61.34, add = TRUE)
divide.world("Oman", "United Arab Emirates", from = 54.33, to = 58.24, add = TRUE)
divide.world("Oman", "Yemen", from = 54.33, to = 57.4, add = TRUE)
divide.world("Pakistan", "Tajikistan", from = 71.9, to = 74.7, add = TRUE)
divide.world("Palau", "Papua New Guinea", from = 136.57, to = 144.8, add = TRUE)
divide.world("Palau", "Philippines", from = 124.88, to = 132.3, add = TRUE)
divide.world("Palau", "Taiwan", from = 132.3, to = 133.65, add = TRUE)
divide.world("Palestinian Territory", "Saudi Arabia", from = 37.6, to = 38.1, add = TRUE)
divide.world("Panama", "Venezuela", from = -73.48, to = -73.35, add = TRUE)
divide.world("Papua New Guinea", "Solomon Islands", from = 153.559, to = 153.574, add = TRUE)
divide.world("Paraguay", "Uruguay", from = -56.62, to = -43.72, add = TRUE)
divide.world("Philippines", "Taiwan", from = 119.45, to = 132.3, add = TRUE)
divide.world("Philippines", "Vietnam", from = 111.1, to = 111.16, add = TRUE)
divide.world("Poland", "Slovakia", from = 18.25, to = 19.7, add = TRUE)
divide.world("Poland", "Ukraine", from = 24.95, to = 25.7, add = TRUE)
divide.world("Portugal", "Spain", from = -10.4, to = -5.9, add = TRUE)
divide.world("Portugal", "Western Sahara", from = -37.7, to = -15, add = TRUE)
divide.world("Puerto Rico", "Saint Kitts and Nevis", from = -65.75, to = -61.5, add = TRUE)
divide.world("Puerto Rico", "Venezuela", from = -68.082, to = -65.75, add = TRUE)
divide.world("Qatar", "Saudi Arabia", from = 49.22, to = 49.99, add = TRUE)
divide.world("Qatar", "Yemen", from = 49.99, to = 50.8, add = TRUE)
divide.world("Qatar", "United Arab Emirates", from = 50.8, to = 54.1, add = TRUE)
divide.world("Romania", "Serbia", from = 23.3, to = 23.61, add = TRUE)
divide.world("Romania", "Turkey", from = 27.85, to = 31.3, add = TRUE)
divide.world("Russia", "Ukraine", from = 33.3, to = 41.7, add = TRUE)
divide.world("Saint Kitts and Nevis", "Venezuela", from = -65.75, to = -65.4, add = TRUE)
divide.world("Saint Lucia", "Saint Vincent and the Grenadines", from = -63.3, to = -60.41, add = TRUE)
divide.world("Samoa", "Tonga", from = -176.6, to = -173.78, add = TRUE)
divide.world("Samoa", "Tuvalu", from = -177.8, to = -164.8, add = TRUE)
divide.world("San Marino", "Slovenia", from = 11.7, to = 14.75, add = TRUE)
divide.world("San Marino", "Vatican", from = 10.01, to = 13.1, add = TRUE)
divide.world("Saudi Arabia", "Yemen", from = 41.547, to = 49.99, add = TRUE)
divide.world("Seychelles", "Somalia", from = 50, to = 57.55, add = TRUE)
divide.world("Solomon Islands", "Vanuatu", from = 160.1, to = 168.8, add = TRUE)
divide.world("Somalia", "Yemen", from = 57.05, to = 57.4, add = TRUE)
divide.world("South Korea", "Taiwan", from = 119.7, to = 131.7, add = TRUE)
divide.world("Spain", "United Kingdom", from = -7.2, to = -6.9, add = TRUE)
divide.world("Sri Lanka", "Thailand", from = 90, to = 91.18, add = TRUE)
divide.world("Tajikistan", "Turkmenistan", from = 63.38, to = 63.76, add = TRUE)
divide.world("Tajikistan", "Uzbekistan", from = 63.38, to = 73.3, add = TRUE)
divide.world("Trinidad and Tobago", "Venezuela", from = -64.21, to = -64.013, add = TRUE)
divide.world("Tunisia", "Vatican", from = 8.2, to = 11.1, add = TRUE)
divide.world("Turkmenistan", "United Arab Emirates", from = 57.65, to = 58.24, add = TRUE)
divide.world("Turkmenistan", "Uzbekistan", from = 59.4, to = 63.38, add = TRUE)
divide.world("Tuvalu", "Vanuatu", from = 170.1, to = 173.6, add = TRUE)
divide.world("United Arab Emirates", "Yemen", from = 50.8, to = 54.33, add = TRUE)
lines(c(35.225, 35.225), c(27.4, 32.83), col = "red")

pos <- rep(1, length(countries))
names(pos) <- countries
pos["Armenia"] <- 2
pos["Austria"] <- 2
pos["Bosnia and Herzegovina"] <- 2
pos["Croatia"] <- 4
pos["Finland"] <- 3
pos["Georgia"] <- 2
pos["Israel"] <- 2
pos["Italy"] <- 4
pos["Jordan"] <- 4
pos["Kosovo"] <- 3
pos["Lebanon"] <- 3
pos["Liechtenstein"] <- 3
pos["Montenegro"] <- 2
pos["Netherlands"] <- 3
pos["San Marino"] <- 3
pos["Serbia"] <- 3
pos["Slovenia"] <- 2
pos["Syria"] <- 4
pos["Vatican"] <- 2
country.names <- countries
names(country.names) <- countries
country.names["Bosnia and Herzegovina"] <- "Bosnia and\nHerzegovina"
country.names["Palestinian Territory"] <- "Palestinian\nTerritory"
points(capitals[countries, c("Longitude", "Latitude")],
       pch = 16, cex = 0.7, col = "green")
#text(capitals[countries, c("Longitude", "Latitude")],
#     labels = country.names, cex = 0.5, pos = pos)