divide.world("Slovenia", "Croatia", from = 14.7, to = 15.6,
             #xlim = c(24, 30),
             ylim = c(40, 50), axes = TRUE)
divide.world("Slovenia", "San Marino", from = 11.6, to = 14.7, add = TRUE)
divide.world("Slovenia", "Austria", from = 12.9, to = 15.6, add = TRUE)
divide.world("Croatia", "Austria", from = 15.6, to = 16.53, add = TRUE)
divide.world("Slovenia", "Liechtenstein", from = 11.6, to = 12.7, add = TRUE)
divide.world("Switzerland", "Liechtenstein", from = 8.15, to = 8.8, add = TRUE)
divide.world("Switzerland", "France", from = 4, to = 4.9, add = TRUE)
divide.world("Luxembourg", "France", from = 4, to = 4.9, add = TRUE)
divide.world("Luxembourg", "Switzerland", from = 4.9, to = 8.15, add = TRUE)
divide.world("Luxembourg", "Liechtenstein", from = 8.15, to = 10.3, add = TRUE)
divide.world("Monaco", "Switzerland", from = 4, to = 8.8, add = TRUE)
divide.world("Monaco", "Liechtenstein", from = 8.8, to = 9.83, add = TRUE)
divide.world("Monaco", "Vatican", from = 4, to = 10, add = TRUE)
divide.world("San Marino", "Italy", from = 13.1, to = 15.38, add = TRUE)
divide.world("San Marino", "Monaco", from = 9.83, to = 10, add = TRUE)
divide.world("San Marino", "Liechtenstein", from = 9.83, to = 11.6, add = TRUE)
divide.world("San Marino", "Croatia", from = 14.7, to = 15.4, add = TRUE)
divide.world("Italy", "Vatican", from = 10, to = 13.1, add = TRUE)
divide.world("San Marino", "Vatican", from = 10, to = 13.1, add = TRUE)
divide.world("Luxembourg", "Belgium", from = 4, to = 8, add = TRUE)
divide.world("Czech Republic", "Austria", from = 12.9, to = 17.05, add = TRUE)
divide.world("Czech Republic", "Slovenia", from = 12.7, to = 12.9, add = TRUE)
divide.world("Czech Republic", "Liechtenstein", from = 10.3, to = 12.7, add = TRUE)
divide.world("Czech Republic", "Luxembourg", from = 10.1, to = 10.3, add = TRUE)
divide.world("Austria", "Slovakia", from = 16.53, to = 17.05, add = TRUE)
divide.world("Czech Republic", "Slovakia", from = 17.05, to = 18.4, add = TRUE)
divide.world("Croatia", "Slovakia", from = 16.53, to = 17.3, add = TRUE)
divide.world("Poland", "Slovakia", from = 18.4, to = 19.7, add = TRUE)
divide.world("Hungary", "Slovakia", from = 17.3, to = 19.7, add = TRUE)
divide.world("Croatia", "Hungary", from = 17.3, to = 18.5, add = TRUE)
divide.world("Poland", "Hungary", from = 19.7, to = 24.7, add = TRUE)
divide.world("Croatia", "Bosnia and Herzegovina", from = 15.4, to = 18.3, add = TRUE)
divide.world("Bosnia and Herzegovina", "Italy", from = 15.38, to = 15.9, add = TRUE)
divide.world("Bosnia and Herzegovina", "San Marino", from = 15.38, to = 15.4, add = TRUE)
divide.world("Bosnia and Herzegovina", "Serbia", from = 18.3, to = 20.05, add = TRUE)
divide.world("Serbia", "Hungary", from = 18.5, to = 23.61, add = TRUE)
divide.world("Serbia", "Croatia", from = 18.3, to = 18.5, add = TRUE)
divide.world("Bosnia and Herzegovina", "Montenegro", from = 15.9, to = 19.99, add = TRUE)
divide.world("Montenegro", "Italy", from = 15.9, to = 16.06, add = TRUE)
divide.world("Montenegro", "Kosovo", from = 19.99, to = 20.31, add = TRUE)
divide.world("Bosnia and Herzegovina", "Kosovo", from = 19.99, to = 20.05, add = TRUE)
divide.world("Kosovo", "Serbia", from = 20.05, to = 22.21, add = TRUE)
divide.world("Montenegro", "Albania", from = 16.06, to = 20.3, add = TRUE)
divide.world("Albania", "Italy", from = 15, to = 16.06, add = TRUE)
divide.world("Macedonia", "Kosovo", from = 20.31, to = 22.25, add = TRUE)
divide.world("Macedonia", "Montenegro", from = 20.3, to = 20.31, add = TRUE)
divide.world("Albania", "Macedonia", from = 20.3, to = 22, add = TRUE)
divide.world("Greece", "Macedonia", from = 22, to = 23.7, add = TRUE)
divide.world("Greece", "Albania", from = 21, to = 22, add = TRUE)
divide.world("Bulgaria", "Macedonia", from = 22.25, to = 23.7, add = TRUE)
divide.world("Bulgaria", "Greece", from = 23.7, to = 30, add = TRUE)
divide.world("Bulgaria", "Kosovo", from = 22.21, to = 22.25, add = TRUE)
divide.world("Bulgaria", "Serbia", from = 22.21, to = 23.3, add = TRUE)
divide.world("Bulgaria", "Romania", from = 23.3, to = 30, add = TRUE)
divide.world("Serbia", "Romania", from = 23.3, to = 23.61, add = TRUE)
divide.world("Romania", "Hungary", from = 23.61, to = 25, add = TRUE)
divide.world("Ukraine", "Poland", from = 24.7, to = 26, add = TRUE)
divide.world("Ukraine", "Hungary", from = 24.7, to = 25, add = TRUE)
divide.world("Romania", "Ukraine", from = 25, to = 26, add = TRUE)
